# Generated by Django 3.2.6 on 2021-08-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineBookingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=15)),
                ('uid', models.CharField(max_length=12)),
                ('ref_id', models.IntegerField(max_length=9)),
                ('total_member', models.IntegerField()),
                ('yob', models.IntegerField()),
                ('first_booking', models.DateField()),
                ('second_booking', models.DateField()),
            ],
            options={
                'db_table': 'vaccinationbooking',
            },
        ),
    ]
