# Generated by Django 3.2.6 on 2021-08-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vaccineslot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinebookingclass',
            old_name='yob',
            new_name='age',
        ),
    ]
