# Generated by Django 3.2.6 on 2021-09-01 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_member', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='vaccinebookingclass',
            old_name='username',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='vaccinebookingclass',
            name='ref_id',
        ),
        migrations.AlterModelTable(
            name='vaccinebookingclass',
            table='member_info_table',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
