# Generated by Django 3.2.6 on 2021-09-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210902_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_info_class',
            name='uid',
        ),
        migrations.AddField(
            model_name='vaccinebookingclass',
            name='pincode',
            field=models.IntegerField(default='null'),
        ),
        migrations.AlterField(
            model_name='vaccineslot',
            name='pin_code',
            field=models.IntegerField(default='null'),
        ),
    ]
