# Generated by Django 3.2.6 on 2021-09-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210902_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_info_class',
            name='uid',
            field=models.IntegerField(default='null'),
        ),
    ]
