# Generated by Django 3.2.6 on 2021-09-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210902_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineslot',
            name='available_vaccine',
        ),
        migrations.RemoveField(
            model_name='vaccineslot',
            name='total_vaccine',
        ),
        migrations.AddField(
            model_name='vaccineslot',
            name='vaccine_12',
            field=models.IntegerField(default='null'),
        ),
        migrations.AddField(
            model_name='vaccineslot',
            name='vaccine_18',
            field=models.IntegerField(default='null'),
        ),
        migrations.AddField(
            model_name='vaccineslot',
            name='vaccine_45',
            field=models.IntegerField(default='null'),
        ),
        migrations.AddField(
            model_name='vaccineslot',
            name='vaccine_60',
            field=models.IntegerField(default='null'),
        ),
    ]
