# Generated by Django 3.2.6 on 2021-09-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210903_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_info_class',
            name='first_booking',
            field=models.DateField(default='null'),
        ),
        migrations.AlterField(
            model_name='member_info_class',
            name='second_booking',
            field=models.DateField(default='null'),
        ),
    ]
