# Generated by Django 3.2.6 on 2021-09-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210903_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_info_class',
            name='first_booking',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='member_info_class',
            name='second_booking',
            field=models.DateField(),
        ),
    ]
