# Generated by Django 3.2.6 on 2021-10-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210903_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinebookingclass',
            name='uid',
            field=models.CharField(max_length=100),
        ),
    ]
