# Generated by Django 3.2.6 on 2021-10-09 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20211009_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='rishuVaccineSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('district', models.CharField(max_length=200)),
                ('pincode', models.IntegerField(default='null')),
                ('date', models.CharField(max_length=200)),
                ('vaccine_type', models.CharField(max_length=200)),
                ('min_age_limit', models.IntegerField()),
                ('available_capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'rishuVaccineSlot',
            },
        ),
    ]
